import { AppProject, ComponentNode } from '@/types/schema';
import { generateId } from '@/lib/utils';

export function createModernStoreTemplate(): AppProject {
  const rootId = generateId('root');
  const navbarId = generateId('nav');
  const heroSectionId = generateId('hero_sec');
  const heroBadgeId = generateId('badge');
  const heroHeadingId = generateId('heading');
  const heroTextId = generateId('text');
  const heroBtnRowId = generateId('btn_row');
  const heroBtn1Id = generateId('btn_primary');
  const heroBtn2Id = generateId('btn_secondary');

  const statsRowId = generateId('stats_row');
  const stat1Id = generateId('stat1');
  const stat2Id = generateId('stat2');
  const stat3Id = generateId('stat3');

  const productsSectionId = generateId('prod_sec');
  const prodHeadingId = generateId('prod_head');
  const prodRepeaterId = generateId('prod_rep');
  const prodCardId = generateId('prod_card');
  const prodImgId = generateId('prod_img');
  const prodTitleId = generateId('prod_title');
  const prodPriceId = generateId('prod_price');
  const prodAddBtnId = generateId('prod_add_btn');

  const footerSectionId = generateId('footer');
  const footerTextId = generateId('footer_text');

  const nodes: Record<string, ComponentNode> = {
    [rootId]: {
      id: rootId,
      type: 'container',
      name: 'Page Root',
      props: {},
      styles: {
        display: 'flex',
        flexDirection: 'column',
        gap: '32px',
        paddingTop: '24px',
        paddingBottom: '60px',
        paddingLeft: '32px',
        paddingRight: '32px',
        width: '100%',
        minHeight: '100vh',
        backgroundColor: '#07080C',
        color: '#FFFFFF',
      },
      children: [navbarId, heroSectionId, statsRowId, productsSectionId, footerSectionId],
      parentId: null,
    },
    [navbarId]: {
      id: navbarId,
      type: 'navbar',
      name: 'Top Navigation',
      props: {
        brandName: 'NEXUS APPAREL',
        links: ['New Drops', 'Collections', 'Techwear', 'Sale'],
      },
      styles: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingTop: '16px',
        paddingBottom: '16px',
        paddingLeft: '28px',
        paddingRight: '28px',
        backgroundColor: '#0F1118',
        borderRadius: '16px',
        borderWidth: '1px',
        borderColor: '#1F2433',
        width: '100%',
      },
      children: [],
      parentId: rootId,
    },
    [heroSectionId]: {
      id: heroSectionId,
      type: 'section',
      name: 'Hero Section',
      props: {},
      styles: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        textAlign: 'center',
        paddingTop: '64px',
        paddingBottom: '64px',
        paddingLeft: '32px',
        paddingRight: '32px',
        gap: '20px',
        backgroundColor: 'linear-gradient(180deg, #111420 0%, #0C0E17 100%)',
        borderRadius: '24px',
        borderWidth: '1px',
        borderColor: '#23293D',
        width: '100%',
        boxShadow: '0 20px 40px -15px rgba(0,0,0,0.5)',
      },
      children: [heroBadgeId, heroHeadingId, heroTextId, heroBtnRowId],
      parentId: rootId,
    },
    [heroBadgeId]: {
      id: heroBadgeId,
      type: 'badge',
      name: 'Hero Tag',
      props: { text: '⚡ LIMITED RELEASE • AUTUMN 2026' },
      styles: {
        display: 'inline-flex',
        fontSize: '12px',
        fontWeight: '700',
        color: '#818CF8',
        backgroundColor: 'rgba(99, 102, 241, 0.12)',
        paddingTop: '6px',
        paddingBottom: '6px',
        paddingLeft: '14px',
        paddingRight: '14px',
        borderRadius: '9999px',
        borderWidth: '1px',
        borderColor: 'rgba(99, 102, 241, 0.3)',
      },
      children: [],
      parentId: heroSectionId,
    },
    [heroHeadingId]: {
      id: heroHeadingId,
      type: 'heading',
      name: 'Hero Title',
      props: { text: 'Engineered For The Cyber Era', level: 'h1' },
      styles: {
        fontSize: '48px',
        fontWeight: '800',
        color: '#FFFFFF',
        letterSpacing: '-0.03em',
        lineHeight: '1.1',
        maxWidth: '820px',
      },
      responsive: {
        mobile: {
          fontSize: '32px',
        },
      },
      children: [],
      parentId: heroSectionId,
    },
    [heroTextId]: {
      id: heroTextId,
      type: 'text',
      name: 'Hero Subtitle',
      props: {
        text: 'Weather-resistant materials crafted with minimalist silhouettes. Discover the pinnacle of performance outerwear.',
      },
      styles: {
        fontSize: '18px',
        color: '#94A3B8',
        maxWidth: '640px',
        lineHeight: '1.6',
      },
      children: [],
      parentId: heroSectionId,
    },
    [heroBtnRowId]: {
      id: heroBtnRowId,
      type: 'row',
      name: 'CTA Button Row',
      props: {},
      styles: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'center',
        gap: '16px',
        marginTop: '12px',
        flexWrap: 'wrap',
      },
      children: [heroBtn1Id, heroBtn2Id],
      parentId: heroSectionId,
    },
    [heroBtn1Id]: {
      id: heroBtn1Id,
      type: 'button',
      name: 'Shop Collection Button',
      props: { text: 'Shop Collection', variant: 'primary', icon: 'ArrowRight' },
      styles: {
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        paddingTop: '14px',
        paddingBottom: '14px',
        paddingLeft: '28px',
        paddingRight: '28px',
        backgroundColor: '#4F46E5',
        color: '#FFFFFF',
        fontSize: '15px',
        fontWeight: '600',
        borderRadius: '12px',
        cursor: 'pointer',
      },
      events: [
        {
          id: generateId('evt'),
          trigger: 'click',
          actionType: 'toast',
          payload: { message: 'Browsing all products!' },
        },
      ],
      children: [],
      parentId: heroBtnRowId,
    },
    [heroBtn2Id]: {
      id: heroBtn2Id,
      type: 'button',
      name: 'Lookbook Button',
      props: { text: 'View Lookbook', variant: 'outline' },
      styles: {
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        paddingTop: '14px',
        paddingBottom: '14px',
        paddingLeft: '28px',
        paddingRight: '28px',
        backgroundColor: 'transparent',
        borderWidth: '1px',
        borderColor: '#374151',
        color: '#E5E7EB',
        fontSize: '15px',
        fontWeight: '600',
        borderRadius: '12px',
        cursor: 'pointer',
      },
      children: [],
      parentId: heroBtnRowId,
    },
    [statsRowId]: {
      id: statsRowId,
      type: 'row',
      name: 'Metrics Row',
      props: {},
      styles: {
        display: 'grid',
        gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
        gridGap: '20px',
        width: '100%',
      },
      responsive: {
        mobile: {
          gridTemplateColumns: '1fr',
        },
      },
      children: [stat1Id, stat2Id, stat3Id],
      parentId: rootId,
    },
    [stat1Id]: {
      id: stat1Id,
      type: 'statistic',
      name: 'Stat Worldwide',
      props: { title: 'Global Delivery', value: '140+ Countries', change: 'Free over $150', isPositive: true },
      styles: {
        backgroundColor: '#11141E',
        borderRadius: '14px',
        borderWidth: '1px',
        borderColor: '#1E2436',
        paddingTop: '20px',
        paddingBottom: '20px',
        paddingLeft: '24px',
        paddingRight: '24px',
      },
      children: [],
      parentId: statsRowId,
    },
    [stat2Id]: {
      id: stat2Id,
      type: 'statistic',
      name: 'Stat Materials',
      props: { title: 'Waterproof Rating', value: '20,000 mm', change: 'Gore-Tex Pro Grade', isPositive: true },
      styles: {
        backgroundColor: '#11141E',
        borderRadius: '14px',
        borderWidth: '1px',
        borderColor: '#1E2436',
        paddingTop: '20px',
        paddingBottom: '20px',
        paddingLeft: '24px',
        paddingRight: '24px',
      },
      children: [],
      parentId: statsRowId,
    },
    [stat3Id]: {
      id: stat3Id,
      type: 'statistic',
      name: 'Stat Customer Rating',
      props: { title: 'Customer Rating', value: '4.95 / 5.0', change: '12,400+ Verified Reviews', isPositive: true },
      styles: {
        backgroundColor: '#11141E',
        borderRadius: '14px',
        borderWidth: '1px',
        borderColor: '#1E2436',
        paddingTop: '20px',
        paddingBottom: '20px',
        paddingLeft: '24px',
        paddingRight: '24px',
      },
      children: [],
      parentId: statsRowId,
    },
    [productsSectionId]: {
      id: productsSectionId,
      type: 'section',
      name: 'Products Section',
      props: {},
      styles: {
        display: 'flex',
        flexDirection: 'column',
        gap: '24px',
        paddingTop: '32px',
        paddingBottom: '32px',
        paddingLeft: '24px',
        paddingRight: '24px',
        backgroundColor: '#0D0F17',
        borderRadius: '20px',
        borderWidth: '1px',
        borderColor: '#1D2232',
        width: '100%',
      },
      children: [prodHeadingId, prodRepeaterId],
      parentId: rootId,
    },
    [prodHeadingId]: {
      id: prodHeadingId,
      type: 'heading',
      name: 'Products Heading',
      props: { text: 'Featured Collection', level: 'h2' },
      styles: {
        fontSize: '28px',
        fontWeight: '700',
        color: '#FFFFFF',
      },
      children: [],
      parentId: productsSectionId,
    },
    [prodRepeaterId]: {
      id: prodRepeaterId,
      type: 'repeater',
      name: 'Products Repeater',
      props: { collectionKey: 'products', limit: 6 },
      styles: {
        display: 'grid',
        gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
        gridGap: '20px',
        width: '100%',
      },
      responsive: {
        tablet: {
          gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
        },
        mobile: {
          gridTemplateColumns: '1fr',
        },
      },
      children: [prodCardId],
      parentId: productsSectionId,
    },
    [prodCardId]: {
      id: prodCardId,
      type: 'card',
      name: 'Product Card Template',
      props: {},
      styles: {
        display: 'flex',
        flexDirection: 'column',
        gap: '12px',
        paddingTop: '16px',
        paddingBottom: '20px',
        paddingLeft: '16px',
        paddingRight: '16px',
        backgroundColor: '#131622',
        borderRadius: '16px',
        borderWidth: '1px',
        borderColor: '#22283A',
        transition: 'transform 0.2s ease',
      },
      children: [prodImgId, prodTitleId, prodPriceId, prodAddBtnId],
      parentId: prodRepeaterId,
    },
    [prodImgId]: {
      id: prodImgId,
      type: 'image',
      name: 'Product Image',
      props: { src: '{{item.image}}', alt: '{{item.name}}' },
      styles: {
        width: '100%',
        height: '220px',
        borderRadius: '12px',
        objectFit: 'cover',
      },
      children: [],
      parentId: prodCardId,
    },
    [prodTitleId]: {
      id: prodTitleId,
      type: 'heading',
      name: 'Product Title',
      props: { text: '{{item.name}}', level: 'h3' },
      styles: {
        fontSize: '18px',
        fontWeight: '600',
        color: '#FFFFFF',
      },
      children: [],
      parentId: prodCardId,
    },
    [prodPriceId]: {
      id: prodPriceId,
      type: 'text',
      name: 'Product Price',
      props: { text: '{{item.price}}' },
      styles: {
        fontSize: '16px',
        fontWeight: '700',
        color: '#818CF8',
      },
      children: [],
      parentId: prodCardId,
    },
    [prodAddBtnId]: {
      id: prodAddBtnId,
      type: 'button',
      name: 'Add To Cart Button',
      props: { text: 'Add To Bag', variant: 'primary', icon: 'ShoppingBag' },
      styles: {
        paddingTop: '10px',
        paddingBottom: '10px',
        backgroundColor: '#3730A3',
        color: '#FFFFFF',
        borderRadius: '8px',
        fontWeight: '600',
        fontSize: '14px',
        cursor: 'pointer',
      },
      events: [
        {
          id: generateId('evt_cart'),
          trigger: 'click',
          actionType: 'toast',
          payload: { message: 'Added to your bag! 🛍️' },
        },
      ],
      children: [],
      parentId: prodCardId,
    },
    [footerSectionId]: {
      id: footerSectionId,
      type: 'section',
      name: 'Footer',
      props: {},
      styles: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingTop: '28px',
        paddingBottom: '28px',
        paddingLeft: '32px',
        paddingRight: '32px',
        borderTopWidth: '1px',
        borderTopColor: '#1A1E2C',
        color: '#64748B',
        fontSize: '14px',
      },
      children: [footerTextId],
      parentId: rootId,
    },
    [footerTextId]: {
      id: footerTextId,
      type: 'text',
      name: 'Copyright',
      props: { text: '© 2026 Nexus Apparel Inc. Built with Visual App Builder.' },
      styles: { fontSize: '14px', color: '#64748B' },
      children: [],
      parentId: footerSectionId,
    },
  };

  return {
    id: 'proj_modern_store',
    name: 'Modern Streetwear Store',
    version: '1.0.0',
    activePageId: 'page_home',
    pages: [
      {
        id: 'page_home',
        name: 'Home',
        slug: '/',
        rootNodeId: rootId,
        isHome: true,
      },
      {
        id: 'page_catalog',
        name: 'Catalog',
        slug: '/catalog',
        rootNodeId: rootId,
      },
      {
        id: 'page_checkout',
        name: 'Checkout',
        slug: '/checkout',
        rootNodeId: rootId,
      },
    ],
    nodes,
    collections: [
      {
        id: 'col_products',
        name: 'Products',
        key: 'products',
        fields: [
          { id: 'f1', name: 'Name', key: 'name', type: 'text' },
          { id: 'f2', name: 'Price', key: 'price', type: 'text' },
          { id: 'f3', name: 'Image', key: 'image', type: 'image' },
          { id: 'f4', name: 'Stock', key: 'stock', type: 'number' },
        ],
        records: [
          {
            id: '1',
            name: 'Hyperion Tactical Hoodie',
            price: '$180.00',
            image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=600&q=80',
            stock: 14,
          },
          {
            id: '2',
            name: 'Quantum Runner Sneakers',
            price: '$220.00',
            image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80',
            stock: 8,
          },
          {
            id: '3',
            name: 'Neon Cyber Shell Jacket',
            price: '$290.00',
            image: 'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=600&q=80',
            stock: 22,
          },
          {
            id: '4',
            name: 'Obsidian Crossbody Sling',
            price: '$140.00',
            image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80',
            stock: 35,
          },
          {
            id: '5',
            name: 'Aurora Ribbed Beanie',
            price: '$55.00',
            image: 'https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9?auto=format&fit=crop&w=600&q=80',
            stock: 50,
          },
          {
            id: '6',
            name: 'Chrono Titan Carbon Watch',
            price: '$360.00',
            image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&q=80',
            stock: 12,
          },
        ],
      },
    ],
    dataSources: [],
    workflows: [
      {
        id: 'wf_add_cart',
        name: 'Add to Cart Flow',
        triggerEvent: 'click',
        nodes: [
          { id: 'wn1', type: 'trigger', label: 'On Add To Bag Click', config: {} },
          { id: 'wn2', type: 'toast', label: 'Show Success Toast', config: { message: 'Added to cart!' } },
        ],
      },
    ],
    assets: [
      { id: 'a1', name: 'Banner Image', url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe', type: 'image' },
    ],
    theme: {
      primaryColor: '#4F46E5',
      secondaryColor: '#818CF8',
      backgroundColor: '#07080C',
      surfaceColor: '#11131A',
      textColor: '#FFFFFF',
      mutedColor: '#94A3B8',
      borderColor: '#1E2230',
      fontFamily: 'Inter, sans-serif',
      borderRadius: '12px',
    },
    variables: {
      cartCount: 2,
      userCurrency: 'USD',
    },
    settings: {
      title: 'Modern Streetwear Store',
      description: 'Next-gen ecommerce platform built visually',
      isPublished: false,
    },
  };
}

export function createBlankTemplate(): AppProject {
  const rootId = generateId('root');
  const sectionId = generateId('sec');
  const headingId = generateId('heading');
  const textId = generateId('text');
  const btnId = generateId('btn');

  return {
    id: 'proj_blank',
    name: 'Untitled Project',
    version: '1.0.0',
    activePageId: 'page_home',
    pages: [
      {
        id: 'page_home',
        name: 'Home',
        slug: '/',
        rootNodeId: rootId,
        isHome: true,
      },
    ],
    nodes: {
      [rootId]: {
        id: rootId,
        type: 'container',
        name: 'Page Root',
        props: {},
        styles: {
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          minHeight: '100vh',
          backgroundColor: '#0B0D13',
          color: '#FFFFFF',
          paddingTop: '60px',
          paddingBottom: '60px',
          paddingLeft: '24px',
          paddingRight: '24px',
          gap: '24px',
        },
        children: [sectionId],
        parentId: null,
      },
      [sectionId]: {
        id: sectionId,
        type: 'section',
        name: 'Welcome Section',
        props: {},
        styles: {
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          textAlign: 'center',
          gap: '16px',
          paddingTop: '48px',
          paddingBottom: '48px',
          paddingLeft: '48px',
          paddingRight: '48px',
          backgroundColor: '#12151E',
          borderRadius: '20px',
          borderWidth: '1px',
          borderColor: '#212638',
          maxWidth: '680px',
        },
        children: [headingId, textId, btnId],
        parentId: rootId,
      },
      [headingId]: {
        id: headingId,
        type: 'heading',
        name: 'Welcome Heading',
        props: { text: 'Start Building Visually', level: 'h1' },
        styles: {
          fontSize: '36px',
          fontWeight: '700',
          color: '#FFFFFF',
        },
        children: [],
        parentId: sectionId,
      },
      [textId]: {
        id: textId,
        type: 'text',
        name: 'Welcome Text',
        props: {
          text: 'Drag and drop components from the left sidebar to start building your application. Configure properties, add logic, and preview in real time.',
        },
        styles: {
          fontSize: '16px',
          color: '#94A3B8',
          lineHeight: '1.6',
        },
        children: [],
        parentId: sectionId,
      },
      [btnId]: {
        id: btnId,
        type: 'button',
        name: 'Get Started Button',
        props: { text: 'Explore Components', variant: 'primary', icon: 'Plus' },
        styles: {
          paddingTop: '12px',
          paddingBottom: '12px',
          paddingLeft: '24px',
          paddingRight: '24px',
          backgroundColor: '#4F46E5',
          color: '#FFFFFF',
          borderRadius: '10px',
          fontWeight: '600',
          cursor: 'pointer',
        },
        children: [],
        parentId: sectionId,
      },
    },
    collections: [],
    dataSources: [],
    workflows: [],
    assets: [],
    theme: {
      primaryColor: '#4F46E5',
      secondaryColor: '#818CF8',
      backgroundColor: '#0B0D13',
      surfaceColor: '#12151E',
      textColor: '#FFFFFF',
      mutedColor: '#94A3B8',
      borderColor: '#212638',
      fontFamily: 'Inter, sans-serif',
      borderRadius: '10px',
    },
    variables: {},
    settings: {
      title: 'Untitled Project',
      description: 'Built with Visual App Builder',
      isPublished: false,
    },
  };
}
