'use client';

import React, { useState } from 'react';
import { useEditorStore } from '../store/useEditorStore';
import * as Icons from 'lucide-react';
import { ComponentNode } from '@/types/schema';

export const CodeView: React.FC = () => {
  const project = useEditorStore((s) => s.project);
  const showToast = useEditorStore((s) => s.showToast);
  const loadProject = useEditorStore((s) => s.loadProject);

  const [activeSubTab, setActiveSubTab] = useState<'tsx' | 'json'>('tsx');
  const [copied, setCopied] = useState(false);

  const activePage = project.pages.find((p) => p.id === project.activePageId) || project.pages[0];

  // Helper to compile AST component tree into clean React JSX code string
  const generateJsx = (nodeId: string, indent = 4): string => {
    const node: ComponentNode | undefined = project.nodes[nodeId];
    if (!node) return '';

    const spaces = ' '.repeat(indent);
    const childSpaces = ' '.repeat(indent + 2);

    const styleEntries = Object.entries(node.styles)
      .map(([k, v]) => `${k}: '${v}'`)
      .join(', ');

    const styleAttr = styleEntries ? ` style={{ ${styleEntries} }}` : '';

    if (node.type === 'heading') {
      const Tag = node.props.level || 'h1';
      return `${spaces}<${Tag}${styleAttr}>${node.props.text || 'Heading'}</${Tag}>`;
    }

    if (node.type === 'text') {
      return `${spaces}<p${styleAttr}>${node.props.text || 'Text'}</p>`;
    }

    if (node.type === 'button') {
      return `${spaces}<button${styleAttr}>${node.props.text || 'Button'}</button>`;
    }

    if (node.type === 'image') {
      return `${spaces}<img src="${node.props.src || ''}" alt="${node.props.alt || ''}"${styleAttr} />`;
    }

    if (node.children && node.children.length > 0) {
      const childrenJsx = node.children.map((c) => generateJsx(c, indent + 2)).join('\n');
      return `${spaces}<div className="node-${node.type}"${styleAttr}>\n${childrenJsx}\n${spaces}</div>`;
    }

    return `${spaces}<div className="node-${node.type}"${styleAttr} />`;
  };

  const generatedTsx = `// Generated by Apex Studio Visual App Builder
// Page: ${activePage?.name} (${activePage?.slug})

import React from 'react';

export default function ${activePage?.name.replace(/[^a-zA-Z0-9]/g, '') || 'App'}Page() {
  return (
${activePage?.rootNodeId ? generateJsx(activePage.rootNodeId, 4) : '    <div>Empty Page</div>'}
  );
}
`;

  const jsonString = JSON.stringify(project, null, 2);

  const handleCopy = () => {
    const textToCopy = activeSubTab === 'tsx' ? generatedTsx : jsonString;
    navigator.clipboard.writeText(textToCopy);
    setCopied(true);
    showToast('Copied code to clipboard!');
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const content = activeSubTab === 'tsx' ? generatedTsx : jsonString;
    const filename =
      activeSubTab === 'tsx'
        ? `${activePage?.name.toLowerCase() || 'page'}.tsx`
        : `${project.name.toLowerCase().replace(/\s+/g, '_')}_schema.json`;

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
    showToast(`Downloaded ${filename}`);
  };

  const handleImportJson = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = (event) => {
      try {
        const parsed = JSON.parse(event.target?.result as string);
        if (parsed && parsed.nodes && parsed.pages) {
          loadProject(parsed);
        } else {
          showToast('Invalid project schema format.');
        }
      } catch (err) {
        showToast('Error parsing JSON file.');
      }
    };
    reader.readAsText(file);
  };

  return (
    <div className="flex-1 h-full bg-[#08090E] flex flex-col select-none overflow-hidden">
      {/* Top action header */}
      <div className="h-12 bg-[#0E1017] border-b border-[#1E2230] px-4 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <button
            onClick={() => setActiveSubTab('tsx')}
            className={`px-3 py-1 rounded text-xs font-semibold flex items-center gap-1.5 transition-colors ${
              activeSubTab === 'tsx'
                ? 'bg-indigo-600 text-white'
                : 'text-slate-400 hover:text-white bg-[#141620]'
            }`}
          >
            <Icons.Code className="w-3.5 h-3.5" />
            <span>Generated React TSX</span>
          </button>
          <button
            onClick={() => setActiveSubTab('json')}
            className={`px-3 py-1 rounded text-xs font-semibold flex items-center gap-1.5 transition-colors ${
              activeSubTab === 'json'
                ? 'bg-indigo-600 text-white'
                : 'text-slate-400 hover:text-white bg-[#141620]'
            }`}
          >
            <Icons.FileJson className="w-3.5 h-3.5" />
            <span>Project Schema JSON</span>
          </button>
        </div>

        <div className="flex items-center gap-2">
          {activeSubTab === 'json' && (
            <label className="px-3 py-1 bg-[#141620] hover:bg-[#1E2332] text-slate-300 text-xs rounded font-medium cursor-pointer border border-[#23293D] flex items-center gap-1.5">
              <Icons.Upload className="w-3.5 h-3.5" />
              <span>Import JSON</span>
              <input type="file" accept=".json" onChange={handleImportJson} className="hidden" />
            </label>
          )}

          <button
            onClick={handleDownload}
            className="px-3 py-1 bg-[#141620] hover:bg-[#1E2332] text-slate-300 text-xs rounded font-medium border border-[#23293D] flex items-center gap-1.5"
          >
            <Icons.Download className="w-3.5 h-3.5" />
            <span>Download</span>
          </button>

          <button
            onClick={handleCopy}
            className="px-3 py-1 bg-indigo-600 hover:bg-indigo-500 text-white text-xs rounded font-semibold flex items-center gap-1.5 shadow-sm"
          >
            {copied ? <Icons.Check className="w-3.5 h-3.5 text-white" /> : <Icons.Copy className="w-3.5 h-3.5" />}
            <span>{copied ? 'Copied!' : 'Copy Code'}</span>
          </button>
        </div>
      </div>

      {/* Code Editor Content */}
      <div className="flex-1 p-4 overflow-auto font-mono text-xs text-slate-300 bg-[#07080C] leading-relaxed">
        <pre className="selection:bg-indigo-500/30">
          {activeSubTab === 'tsx' ? generatedTsx : jsonString}
        </pre>
      </div>
    </div>
  );
};
