import { ComponentNode, ComponentStyles, ComponentType } from '../schema/component';

export type ComponentCategory =
  | 'Layout'
  | 'Basic'
  | 'Form'
  | 'Navigation'
  | 'Overlay'
  | 'Data'
  | 'Chart'
  | 'Advanced';

export interface ComponentDefinition {
  type: ComponentType;
  label: string;
  category: ComponentCategory;
  icon: string;
  canHaveChildren: boolean;
  defaultProps: Record<string, any>;
  defaultStyles: ComponentStyles;
}

export const COMPONENT_REGISTRY: Record<ComponentType, ComponentDefinition> = {
  container: {
    type: 'container',
    label: 'Container',
    category: 'Layout',
    icon: 'Box',
    canHaveChildren: true,
    defaultProps: {},
    defaultStyles: {
      display: 'flex',
      flexDirection: 'column',
      width: '100%',
      minHeight: '100px',
      padding: '24px',
      gap: '16px',
      backgroundColor: '#FFFFFF',
      borderRadius: '8px',
      border: '1px solid #E2E8F0',
    },
  },
  row: {
    type: 'row',
    label: 'Row',
    category: 'Layout',
    icon: 'Columns',
    canHaveChildren: true,
    defaultProps: {},
    defaultStyles: {
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
      gap: '16px',
      width: '100%',
      padding: '12px',
    },
  },
  column: {
    type: 'column',
    label: 'Column',
    category: 'Layout',
    icon: 'Rows',
    canHaveChildren: true,
    defaultProps: {},
    defaultStyles: {
      display: 'flex',
      flexDirection: 'column',
      gap: '16px',
      width: '100%',
      padding: '12px',
    },
  },
  stack: {
    type: 'stack',
    label: 'Stack',
    category: 'Layout',
    icon: 'Layers',
    canHaveChildren: true,
    defaultProps: {},
    defaultStyles: {
      display: 'flex',
      flexDirection: 'column',
      gap: '8px',
      width: '100%',
    },
  },
  text: {
    type: 'text',
    label: 'Text',
    category: 'Basic',
    icon: 'Type',
    canHaveChildren: false,
    defaultProps: {
      text: 'Start typing something...',
    },
    defaultStyles: {
      color: '#0F172A',
      fontSize: '16px',
      fontFamily: 'Inter, sans-serif',
      lineHeight: '1.5',
    },
  },
  heading: {
    type: 'heading',
    label: 'Heading',
    category: 'Basic',
    icon: 'Heading',
    canHaveChildren: false,
    defaultProps: {
      text: 'Heading Title',
      level: 'h2',
    },
    defaultStyles: {
      color: '#0F172A',
      fontSize: '24px',
      fontWeight: '700',
      fontFamily: 'Inter, sans-serif',
      lineHeight: '1.2',
    },
  },
  paragraph: {
    type: 'paragraph',
    label: 'Paragraph',
    category: 'Basic',
    icon: 'AlignLeft',
    canHaveChildren: false,
    defaultProps: {
      text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    },
    defaultStyles: {
      color: '#475569',
      fontSize: '15px',
      fontFamily: 'Inter, sans-serif',
      lineHeight: '1.6',
    },
  },
  button: {
    type: 'button',
    label: 'Button',
    category: 'Basic',
    icon: 'MousePointerClick',
    canHaveChildren: false,
    defaultProps: {
      text: 'Click me',
    },
    defaultStyles: {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      padding: '10px 20px',
      backgroundColor: '#4F46E5',
      color: '#FFFFFF',
      borderRadius: '6px',
      fontWeight: '500',
      fontSize: '14px',
      border: 'none',
    },
  },
  link: {
    type: 'link',
    label: 'Link',
    category: 'Basic',
    icon: 'ExternalLink',
    canHaveChildren: false,
    defaultProps: {
      text: 'Click here',
      url: 'https://example.com',
      target: '_blank',
    },
    defaultStyles: {
      color: '#4F46E5',
      fontSize: '14px',
      textDecoration: 'underline',
    },
  },
  image: {
    type: 'image',
    label: 'Image',
    category: 'Basic',
    icon: 'Image',
    canHaveChildren: false,
    defaultProps: {
      src: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=600&q=80',
      alt: 'Sample Image',
    },
    defaultStyles: {
      width: '100%',
      height: 'auto',
      borderRadius: '8px',
      objectFit: 'cover',
    },
  },
  icon: {
    type: 'icon',
    label: 'Icon',
    category: 'Basic',
    icon: 'Sparkles',
    canHaveChildren: false,
    defaultProps: {
      iconName: 'Sparkles',
      size: 24,
    },
    defaultStyles: {
      color: '#4F46E5',
      display: 'inline-block',
    },
  },
  divider: {
    type: 'divider',
    label: 'Divider',
    category: 'Layout',
    icon: 'Minus',
    canHaveChildren: false,
    defaultProps: {},
    defaultStyles: {
      width: '100%',
      height: '1px',
      backgroundColor: '#E2E8F0',
      margin: '16px 0',
    },
  },
  spacer: {
    type: 'spacer',
    label: 'Spacer',
    category: 'Layout',
    icon: 'Maximize2',
    canHaveChildren: false,
    defaultProps: {
      height: '32px',
    },
    defaultStyles: {
      width: '100%',
      height: '32px',
    },
  },
  input: {
    type: 'input',
    label: 'Input',
    category: 'Form',
    icon: 'FormInput',
    canHaveChildren: false,
    defaultProps: {
      placeholder: 'Enter text...',
      type: 'text',
    },
    defaultStyles: {
      width: '100%',
      padding: '8px 12px',
      borderRadius: '6px',
      border: '1px solid #CBD5E1',
      fontSize: '14px',
    },
  },
  textarea: {
    type: 'textarea',
    label: 'Textarea',
    category: 'Form',
    icon: 'FileText',
    canHaveChildren: false,
    defaultProps: {
      placeholder: 'Enter long description...',
      rows: 4,
    },
    defaultStyles: {
      width: '100%',
      padding: '8px 12px',
      borderRadius: '6px',
      border: '1px solid #CBD5E1',
      fontSize: '14px',
      minHeight: '80px',
    },
  },
  repeater: {
    type: 'repeater',
    label: 'Repeater',
    category: 'Layout',
    icon: 'Repeat',
    canHaveChildren: true,
    defaultProps: {
      collectionId: '',
      itemVariable: 'item',
      indexVariable: 'index',
      emptyText: 'No records found',
    },
    defaultStyles: {
      display: 'flex',
      flexDirection: 'column',
      width: '100%',
      gap: '12px',
      padding: '8px',
      border: '1px dashed #6366F1',
      borderRadius: '8px',
      minHeight: '60px',
    },
  },

  // ─── Phase 6: Advanced Layout Components ──────────────────────────────────────
  grid: {
    type: 'grid',
    label: 'Grid',
    category: 'Layout',
    icon: 'Grid',
    canHaveChildren: true,
    defaultProps: { columns: 3, rows: 'auto', gap: '16px' },
    defaultStyles: {
      display: 'grid',
      width: '100%',
      gap: '16px',
      padding: '16px',
    },
  },
  split_pane: {
    type: 'split_pane',
    label: 'Split Pane',
    category: 'Layout',
    icon: 'Columns',
    canHaveChildren: true,
    defaultProps: { orientation: 'horizontal', split: '50%' },
    defaultStyles: {
      display: 'flex',
      width: '100%',
      minHeight: '200px',
      gap: '8px',
    },
  },
  sidebar: {
    type: 'sidebar',
    label: 'Sidebar',
    category: 'Layout',
    icon: 'Sidebar',
    canHaveChildren: true,
    defaultProps: { collapsed: false, width: '260px' },
    defaultStyles: {
      display: 'flex',
      flexDirection: 'column',
      width: '260px',
      height: '100%',
      backgroundColor: '#F8FAFC',
      borderRight: '1px solid #E2E8F0',
      padding: '16px',
    },
  },
  sticky_container: {
    type: 'sticky_container',
    label: 'Sticky Container',
    category: 'Layout',
    icon: 'Pin',
    canHaveChildren: true,
    defaultProps: {},
    defaultStyles: {
      position: 'sticky',
      top: '0px',
      zIndex: 10,
      width: '100%',
      backgroundColor: '#FFFFFF',
      padding: '12px 16px',
    },
  },
  scroll_container: {
    type: 'scroll_container',
    label: 'Scroll Container',
    category: 'Layout',
    icon: 'Maximize2',
    canHaveChildren: true,
    defaultProps: { overflowY: 'auto' },
    defaultStyles: {
      overflowY: 'auto',
      maxHeight: '400px',
      width: '100%',
      padding: '16px',
    },
  },
  aspect_ratio_container: {
    type: 'aspect_ratio_container',
    label: 'Aspect Ratio',
    category: 'Layout',
    icon: 'Square',
    canHaveChildren: true,
    defaultProps: { ratio: '16/9' },
    defaultStyles: {
      width: '100%',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  header: {
    type: 'header',
    label: 'Header',
    category: 'Layout',
    icon: 'PanelTop',
    canHaveChildren: true,
    defaultProps: {},
    defaultStyles: {
      display: 'flex',
      alignItems: 'center',
      width: '100%',
      padding: '16px 24px',
      borderBottom: '1px solid #E2E8F0',
    },
  },
  footer: {
    type: 'footer',
    label: 'Footer',
    category: 'Layout',
    icon: 'PanelBottom',
    canHaveChildren: true,
    defaultProps: {},
    defaultStyles: {
      display: 'flex',
      alignItems: 'center',
      width: '100%',
      padding: '24px',
      borderTop: '1px solid #E2E8F0',
    },
  },
  section: {
    type: 'section',
    label: 'Section',
    category: 'Layout',
    icon: 'Square',
    canHaveChildren: true,
    defaultProps: {},
    defaultStyles: {
      display: 'flex',
      flexDirection: 'column',
      width: '100%',
      padding: '32px 0',
    },
  },

  // ─── Phase 6: Advanced Form Components ────────────────────────────────────────
  select: {
    type: 'select',
    label: 'Select',
    category: 'Form',
    icon: 'ChevronDown',
    canHaveChildren: false,
    defaultProps: { placeholder: 'Select an option...', options: ['Option 1', 'Option 2'] },
    defaultStyles: { width: '100%', padding: '8px 12px', borderRadius: '6px', border: '1px solid #CBD5E1' },
  },
  multi_select: {
    type: 'multi_select',
    label: 'Multi Select',
    category: 'Form',
    icon: 'ListFilter',
    canHaveChildren: false,
    defaultProps: { placeholder: 'Select options...', options: ['Option A', 'Option B'] },
    defaultStyles: { width: '100%', padding: '8px 12px', borderRadius: '6px', border: '1px solid #CBD5E1' },
  },
  checkbox: {
    type: 'checkbox',
    label: 'Checkbox',
    category: 'Form',
    icon: 'CheckSquare',
    canHaveChildren: false,
    defaultProps: { label: 'Accept terms', checked: false },
    defaultStyles: { display: 'flex', alignItems: 'center', gap: '8px' },
  },
  checkbox_group: {
    type: 'checkbox_group',
    label: 'Checkbox Group',
    category: 'Form',
    icon: 'CheckSquare',
    canHaveChildren: false,
    defaultProps: { options: ['Red', 'Green', 'Blue'], value: [] },
    defaultStyles: { display: 'flex', flexDirection: 'column', gap: '8px' },
  },
  radio_group: {
    type: 'radio_group',
    label: 'Radio Group',
    category: 'Form',
    icon: 'Radio',
    canHaveChildren: false,
    defaultProps: { options: ['Option 1', 'Option 2'], value: '' },
    defaultStyles: { display: 'flex', flexDirection: 'column', gap: '8px' },
  },
  switch: {
    type: 'switch',
    label: 'Switch',
    category: 'Form',
    icon: 'ToggleLeft',
    canHaveChildren: false,
    defaultProps: { label: 'Enable feature', checked: false },
    defaultStyles: { display: 'flex', alignItems: 'center', gap: '8px' },
  },
  slider: {
    type: 'slider',
    label: 'Slider',
    category: 'Form',
    icon: 'Sliders',
    canHaveChildren: false,
    defaultProps: { min: 0, max: 100, step: 1, value: 50 },
    defaultStyles: { width: '100%' },
  },
  range_slider: {
    type: 'range_slider',
    label: 'Range Slider',
    category: 'Form',
    icon: 'Sliders',
    canHaveChildren: false,
    defaultProps: { min: 0, max: 100, value: [20, 80] },
    defaultStyles: { width: '100%' },
  },
  date_picker: {
    type: 'date_picker',
    label: 'Date Picker',
    category: 'Form',
    icon: 'Calendar',
    canHaveChildren: false,
    defaultProps: { placeholder: 'Pick date...' },
    defaultStyles: { width: '100%', padding: '8px 12px', borderRadius: '6px', border: '1px solid #CBD5E1' },
  },
  time_picker: {
    type: 'time_picker',
    label: 'Time Picker',
    category: 'Form',
    icon: 'Clock',
    canHaveChildren: false,
    defaultProps: { placeholder: 'Pick time...' },
    defaultStyles: { width: '100%', padding: '8px 12px', borderRadius: '6px', border: '1px solid #CBD5E1' },
  },
  datetime_picker: {
    type: 'datetime_picker',
    label: 'Date & Time',
    category: 'Form',
    icon: 'CalendarClock',
    canHaveChildren: false,
    defaultProps: { placeholder: 'Pick date & time...' },
    defaultStyles: { width: '100%', padding: '8px 12px', borderRadius: '6px', border: '1px solid #CBD5E1' },
  },
  file_upload: {
    type: 'file_upload',
    label: 'File Upload',
    category: 'Form',
    icon: 'Upload',
    canHaveChildren: false,
    defaultProps: { label: 'Upload a file', accept: '*/*' },
    defaultStyles: { width: '100%', padding: '24px', border: '2px dashed #CBD5E1', borderRadius: '8px', textAlign: 'center' },
  },
  combobox: {
    type: 'combobox',
    label: 'Combobox',
    category: 'Form',
    icon: 'Search',
    canHaveChildren: false,
    defaultProps: { placeholder: 'Search and select...', options: [] },
    defaultStyles: { width: '100%', padding: '8px 12px', borderRadius: '6px', border: '1px solid #CBD5E1' },
  },
  rich_text: {
    type: 'rich_text',
    label: 'Rich Text',
    category: 'Form',
    icon: 'Edit3',
    canHaveChildren: false,
    defaultProps: { content: '<p>Edit rich text content...</p>' },
    defaultStyles: { width: '100%', minHeight: '120px', padding: '12px', border: '1px solid #CBD5E1', borderRadius: '6px' },
  },
  number_input: {
    type: 'number_input',
    label: 'Number Input',
    category: 'Form',
    icon: 'Hash',
    canHaveChildren: false,
    defaultProps: { placeholder: '0', min: 0 },
    defaultStyles: { width: '100%', padding: '8px 12px', borderRadius: '6px', border: '1px solid #CBD5E1' },
  },
  currency_input: {
    type: 'currency_input',
    label: 'Currency Input',
    category: 'Form',
    icon: 'DollarSign',
    canHaveChildren: false,
    defaultProps: { currency: 'USD', placeholder: '0.00' },
    defaultStyles: { width: '100%', padding: '8px 12px', borderRadius: '6px', border: '1px solid #CBD5E1' },
  },

  // ─── Phase 6: Navigation Components ──────────────────────────────────────────
  navbar: {
    type: 'navbar',
    label: 'Navbar',
    category: 'Navigation',
    icon: 'Menu',
    canHaveChildren: true,
    defaultProps: { brandTitle: 'Brand', links: ['Home', 'About', 'Contact'] },
    defaultStyles: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', width: '100%', padding: '12px 24px', backgroundColor: '#FFFFFF', borderBottom: '1px solid #E2E8F0' },
  },
  sidebar_nav: {
    type: 'sidebar_nav',
    label: 'Sidebar Nav',
    category: 'Navigation',
    icon: 'Navigation',
    canHaveChildren: true,
    defaultProps: { items: ['Dashboard', 'Analytics', 'Settings'] },
    defaultStyles: { display: 'flex', flexDirection: 'column', gap: '4px', width: '100%' },
  },
  tabs: {
    type: 'tabs',
    label: 'Tabs',
    category: 'Navigation',
    icon: 'Folder',
    canHaveChildren: true,
    defaultProps: { tabs: ['Tab 1', 'Tab 2', 'Tab 3'], activeTab: 0 },
    defaultStyles: { display: 'flex', flexDirection: 'column', width: '100%' },
  },
  accordion: {
    type: 'accordion',
    label: 'Accordion',
    category: 'Navigation',
    icon: 'List',
    canHaveChildren: true,
    defaultProps: { items: [{ title: 'Section 1', content: 'Details 1' }] },
    defaultStyles: { width: '100%', border: '1px solid #E2E8F0', borderRadius: '8px' },
  },
  dropdown: {
    type: 'dropdown',
    label: 'Dropdown',
    category: 'Navigation',
    icon: 'ChevronDown',
    canHaveChildren: true,
    defaultProps: { label: 'Options', items: ['Action 1', 'Action 2'] },
    defaultStyles: { position: 'relative', display: 'inline-block' },
  },
  breadcrumbs: {
    type: 'breadcrumbs',
    label: 'Breadcrumbs',
    category: 'Navigation',
    icon: 'ChevronRight',
    canHaveChildren: false,
    defaultProps: { items: ['Home', 'Products', 'Item'] },
    defaultStyles: { display: 'flex', alignItems: 'center', gap: '8px', fontSize: '14px', color: '#64748B' },
  },
  stepper: {
    type: 'stepper',
    label: 'Stepper',
    category: 'Navigation',
    icon: 'ListOrdered',
    canHaveChildren: false,
    defaultProps: { steps: ['Step 1', 'Step 2', 'Step 3'], currentStep: 1 },
    defaultStyles: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', width: '100%', padding: '16px 0' },
  },
  pagination: {
    type: 'pagination',
    label: 'Pagination',
    category: 'Navigation',
    icon: 'ChevronsRight',
    canHaveChildren: false,
    defaultProps: { page: 1, totalPages: 10 },
    defaultStyles: { display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '8px', padding: '8px' },
  },
  menu: {
    type: 'menu',
    label: 'Menu',
    category: 'Navigation',
    icon: 'Menu',
    canHaveChildren: true,
    defaultProps: { items: ['Item 1', 'Item 2'] },
    defaultStyles: { display: 'flex', flexDirection: 'column', gap: '2px', backgroundColor: '#FFFFFF', borderRadius: '6px', padding: '4px', border: '1px solid #E2E8F0' },
  },
  command_menu: {
    type: 'command_menu',
    label: 'Command Menu',
    category: 'Navigation',
    icon: 'Terminal',
    canHaveChildren: false,
    defaultProps: { placeholder: 'Type a command...' },
    defaultStyles: { width: '100%', maxWidth: '600px', backgroundColor: '#FFFFFF', borderRadius: '8px', border: '1px solid #E2E8F0', boxShadow: '0 10px 15px -3px rgba(0,0,0,0.1)' },
  },

  // ─── Phase 6: Overlay Components ─────────────────────────────────────────────
  modal: {
    type: 'modal',
    label: 'Modal Dialog',
    category: 'Overlay',
    icon: 'Maximize',
    canHaveChildren: true,
    defaultProps: { isOpen: true, title: 'Modal Title' },
    defaultStyles: { width: '100%', maxWidth: '500px', padding: '24px', backgroundColor: '#FFFFFF', borderRadius: '12px', boxShadow: '0 20px 25px -5px rgba(0,0,0,0.1)' },
  },
  dialog: {
    type: 'dialog',
    label: 'Dialog',
    category: 'Overlay',
    icon: 'MessageSquare',
    canHaveChildren: true,
    defaultProps: { title: 'Confirmation', message: 'Are you sure?' },
    defaultStyles: { padding: '20px', backgroundColor: '#FFFFFF', borderRadius: '8px', border: '1px solid #E2E8F0' },
  },
  drawer: {
    type: 'drawer',
    label: 'Drawer',
    category: 'Overlay',
    icon: 'PanelRight',
    canHaveChildren: true,
    defaultProps: { side: 'right', isOpen: false },
    defaultStyles: { width: '320px', height: '100%', backgroundColor: '#FFFFFF', boxShadow: '-4px 0 6px -1px rgba(0,0,0,0.1)' },
  },
  popover: {
    type: 'popover',
    label: 'Popover',
    category: 'Overlay',
    icon: 'HelpCircle',
    canHaveChildren: true,
    defaultProps: { triggerText: 'Click me' },
    defaultStyles: { padding: '12px', backgroundColor: '#FFFFFF', borderRadius: '6px', border: '1px solid #E2E8F0', boxShadow: '0 4px 6px -1px rgba(0,0,0,0.1)' },
  },
  tooltip: {
    type: 'tooltip',
    label: 'Tooltip',
    category: 'Overlay',
    icon: 'MessageCircle',
    canHaveChildren: true,
    defaultProps: { content: 'Tooltip hint' },
    defaultStyles: { display: 'inline-block' },
  },
  toast: {
    type: 'toast',
    label: 'Toast',
    category: 'Overlay',
    icon: 'Bell',
    canHaveChildren: false,
    defaultProps: { message: 'Notification message', type: 'info' },
    defaultStyles: { padding: '12px 16px', backgroundColor: '#1E293B', color: '#FFFFFF', borderRadius: '8px' },
  },
  alert: {
    type: 'alert',
    label: 'Alert Banner',
    category: 'Overlay',
    icon: 'AlertTriangle',
    canHaveChildren: true,
    defaultProps: { title: 'Notice', message: 'Important information', severity: 'info' },
    defaultStyles: { padding: '16px', borderRadius: '8px', border: '1px solid #93C5FD', backgroundColor: '#EFF6FF' },
  },
  notification: {
    type: 'notification',
    label: 'Notification',
    category: 'Overlay',
    icon: 'Bell',
    canHaveChildren: false,
    defaultProps: { title: 'New Alert' },
    defaultStyles: { padding: '12px', borderRadius: '6px', backgroundColor: '#F8FAFC' },
  },

  // ─── Phase 6: Data Display Components ────────────────────────────────────────
  data_table: {
    type: 'data_table',
    label: 'Data Table',
    category: 'Data',
    icon: 'Table',
    canHaveChildren: false,
    defaultProps: { collectionId: '', columns: [], pageSize: 10, enableSelection: true, enableSort: true, enableFilter: true, enableSearch: true },
    defaultStyles: { width: '100%', border: '1px solid #E2E8F0', borderRadius: '8px', overflow: 'hidden' },
  },
  card: {
    type: 'card',
    label: 'Card',
    category: 'Data',
    icon: 'Square',
    canHaveChildren: true,
    defaultProps: { title: 'Card Title', subtitle: 'Card Subtitle' },
    defaultStyles: { display: 'flex', flexDirection: 'column', width: '100%', padding: '20px', borderRadius: '10px', border: '1px solid #E2E8F0', backgroundColor: '#FFFFFF' },
  },
  card_grid: {
    type: 'card_grid',
    label: 'Card Grid',
    category: 'Data',
    icon: 'Grid',
    canHaveChildren: true,
    defaultProps: { columns: 3 },
    defaultStyles: { display: 'grid', gap: '20px', width: '100%' },
  },
  tree: {
    type: 'tree',
    label: 'Tree View',
    category: 'Data',
    icon: 'GitBranch',
    canHaveChildren: false,
    defaultProps: { data: [] },
    defaultStyles: { width: '100%', padding: '12px' },
  },
  list: {
    type: 'list',
    label: 'List',
    category: 'Data',
    icon: 'List',
    canHaveChildren: true,
    defaultProps: { items: ['Item 1', 'Item 2'] },
    defaultStyles: { display: 'flex', flexDirection: 'column', width: '100%', border: '1px solid #E2E8F0', borderRadius: '8px' },
  },
  timeline: {
    type: 'timeline',
    label: 'Timeline',
    category: 'Data',
    icon: 'Clock',
    canHaveChildren: false,
    defaultProps: { events: [{ title: 'Created', time: '10:00 AM' }] },
    defaultStyles: { display: 'flex', flexDirection: 'column', gap: '16px', padding: '16px' },
  },
  badge: {
    type: 'badge',
    label: 'Badge',
    category: 'Data',
    icon: 'Tag',
    canHaveChildren: false,
    defaultProps: { text: 'Badge', variant: 'primary' },
    defaultStyles: { display: 'inline-flex', padding: '2px 8px', borderRadius: '9999px', fontSize: '12px', fontWeight: '500', backgroundColor: '#EEF2FF', color: '#4F46E5' },
  },
  avatar: {
    type: 'avatar',
    label: 'Avatar',
    category: 'Data',
    icon: 'User',
    canHaveChildren: false,
    defaultProps: { name: 'User', src: '' },
    defaultStyles: { width: '40px', height: '40px', borderRadius: '9999px', backgroundColor: '#E2E8F0', display: 'flex', alignItems: 'center', justifyContent: 'center' },
  },
  status: {
    type: 'status',
    label: 'Status Indicator',
    category: 'Data',
    icon: 'Circle',
    canHaveChildren: false,
    defaultProps: { status: 'active', label: 'Active' },
    defaultStyles: { display: 'inline-flex', alignItems: 'center', gap: '6px', fontSize: '14px' },
  },
  progress: {
    type: 'progress',
    label: 'Progress Bar',
    category: 'Data',
    icon: 'Activity',
    canHaveChildren: false,
    defaultProps: { value: 65, max: 100 },
    defaultStyles: { width: '100%', height: '8px', borderRadius: '4px', backgroundColor: '#E2E8F0' },
  },
  statistic_kpi: {
    type: 'statistic_kpi',
    label: 'Statistic / KPI',
    category: 'Data',
    icon: 'TrendingUp',
    canHaveChildren: false,
    defaultProps: { title: 'Total Revenue', value: '$45,200', change: '+12.5%', isPositive: true },
    defaultStyles: { display: 'flex', flexDirection: 'column', padding: '20px', borderRadius: '10px', backgroundColor: '#FFFFFF', border: '1px solid #E2E8F0' },
  },
  empty_state: {
    type: 'empty_state',
    label: 'Empty State',
    category: 'Data',
    icon: 'Inbox',
    canHaveChildren: false,
    defaultProps: { title: 'No Data Available', description: 'Get started by creating your first entry.' },
    defaultStyles: { display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: '48px', textAlign: 'center', color: '#64748B' },
  },
  skeleton: {
    type: 'skeleton',
    label: 'Skeleton Loader',
    category: 'Data',
    icon: 'Loader',
    canHaveChildren: false,
    defaultProps: {},
    defaultStyles: { width: '100%', height: '20px', borderRadius: '4px', backgroundColor: '#E2E8F0' },
  },

  // ─── Phase 6: Charts & Maps ──────────────────────────────────────────────────
  chart: {
    type: 'chart',
    label: 'Chart',
    category: 'Chart',
    icon: 'BarChart2',
    canHaveChildren: false,
    defaultProps: { chartType: 'line', title: 'Analytics Chart', dataset: [] },
    defaultStyles: { width: '100%', minHeight: '300px', padding: '16px', backgroundColor: '#FFFFFF', borderRadius: '8px', border: '1px solid #E2E8F0' },
  },
  map: {
    type: 'map',
    label: 'Map',
    category: 'Advanced',
    icon: 'MapPin',
    canHaveChildren: false,
    defaultProps: { center: [37.7749, -122.4194], zoom: 12, markers: [] },
    defaultStyles: { width: '100%', minHeight: '350px', borderRadius: '8px', border: '1px solid #E2E8F0' },
  },
  chart_line: {
    type: 'chart_line',
    label: 'Line Chart',
    category: 'Chart',
    icon: 'TrendingUp',
    canHaveChildren: false,
    defaultProps: { chartType: 'line', title: 'Line Chart', dataset: [] },
    defaultStyles: { width: '100%', minHeight: '300px', padding: '16px', backgroundColor: '#FFFFFF', borderRadius: '8px', border: '1px solid #E2E8F0' },
  },
  chart_bar: {
    type: 'chart_bar',
    label: 'Bar Chart',
    category: 'Chart',
    icon: 'BarChart2',
    canHaveChildren: false,
    defaultProps: { chartType: 'bar', title: 'Bar Chart', dataset: [] },
    defaultStyles: { width: '100%', minHeight: '300px', padding: '16px', backgroundColor: '#FFFFFF', borderRadius: '8px', border: '1px solid #E2E8F0' },
  },
  chart_area: {
    type: 'chart_area',
    label: 'Area Chart',
    category: 'Chart',
    icon: 'Activity',
    canHaveChildren: false,
    defaultProps: { chartType: 'area', title: 'Area Chart', dataset: [] },
    defaultStyles: { width: '100%', minHeight: '300px', padding: '16px', backgroundColor: '#FFFFFF', borderRadius: '8px', border: '1px solid #E2E8F0' },
  },
  chart_pie: {
    type: 'chart_pie',
    label: 'Pie Chart',
    category: 'Chart',
    icon: 'PieChart',
    canHaveChildren: false,
    defaultProps: { chartType: 'pie', title: 'Pie Chart', dataset: [] },
    defaultStyles: { width: '100%', minHeight: '300px', padding: '16px', backgroundColor: '#FFFFFF', borderRadius: '8px', border: '1px solid #E2E8F0' },
  },
  chart_donut: {
    type: 'chart_donut',
    label: 'Donut Chart',
    category: 'Chart',
    icon: 'Disc',
    canHaveChildren: false,
    defaultProps: { chartType: 'donut', title: 'Donut Chart', dataset: [] },
    defaultStyles: { width: '100%', minHeight: '300px', padding: '16px', backgroundColor: '#FFFFFF', borderRadius: '8px', border: '1px solid #E2E8F0' },
  },
  chart_sparkline: {
    type: 'chart_sparkline',
    label: 'Sparkline',
    category: 'Chart',
    icon: 'Activity',
    canHaveChildren: false,
    defaultProps: { chartType: 'sparkline', title: 'Sparkline', dataset: [] },
    defaultStyles: { width: '100%', minHeight: '60px', padding: '4px' },
  },
  map_container: {
    type: 'map_container',
    label: 'Map Container',
    category: 'Advanced',
    icon: 'MapPin',
    canHaveChildren: false,
    defaultProps: { center: [37.7749, -122.4194], zoom: 12, markers: [] },
    defaultStyles: { width: '100%', minHeight: '350px', borderRadius: '8px', border: '1px solid #E2E8F0' },
  },
  alert_banner: {
    type: 'alert_banner',
    label: 'Alert Banner',
    category: 'Overlay',
    icon: 'AlertTriangle',
    canHaveChildren: true,
    defaultProps: { title: 'Notice', message: 'Important information', severity: 'info' },
    defaultStyles: { padding: '16px', borderRadius: '8px', border: '1px solid #93C5FD', backgroundColor: '#EFF6FF' },
  },
  reusable_instance: {
    type: 'reusable_instance',
    label: 'Reusable Component',
    category: 'Advanced',
    icon: 'Layers',
    canHaveChildren: true,
    defaultProps: { componentDefinitionId: '' },
    defaultStyles: { width: '100%' },
  },
};

export function createDefaultNode(type: ComponentType, id: string, name?: string): ComponentNode {
  const def = COMPONENT_REGISTRY[type] || COMPONENT_REGISTRY.container;
  return {
    id,
    type,
    name: name || def.label,
    props: JSON.parse(JSON.stringify(def.defaultProps)),
    styles: JSON.parse(JSON.stringify(def.defaultStyles)),
    children: [],
  };
}
